version: "3"
services:
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    container_name: postamat-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: postamats

volumes:
  postgres: {}
