services:
  parcelsnginx:
    image: nginx:1.19.7-alpine
    container_name: parcels-nginx
    depends_on:
      - parcelsface
      - parcelsserver
      - parcelspostgres
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: parcels.explainit.ru,www.parcels.explainit.ru
      LETSENCRYPT_HOST: parcels.explainit.ru,www.parcels.explainit.ru
  parcelsserver:
    build:
      context: server/
      dockerfile: Dockerfile.server
    container_name: parcels-server
    depends_on:
      - parcelspostgres
    restart: unless-stopped
    command: sh -c "yarn run migrate:dev && yarn start:prod"
    environment:
      MODE: server
      PORT: 3001
    env_file:
      - .env
    ports:
      - 3001:3001
  parcelsface:
    build:
      context: face/
      dockerfile: Dockerfile.server
    container_name: parcels-face
    depends_on:
      - parcelsserver
      - parcelspostgres
    restart: unless-stopped
    command: yarn run start
    environment:
      MODE: server
  parcelspostgres:
    image: postgres:16.2
    restart: unless-stopped
    container_name: parcels-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
