services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: parcels-nginx
    depends_on:
      - face
      - server
      - postgres
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
    environment:
      VIRTUAL_HOST: parcels.explainit.ru,www.parcels.explainit.ru
      LETSENCRYPT_HOST: parcels.explainit.ru,www.parcels.explainit.ru
  server:
    build:
      context: server/
      dockerfile: Dockerfile.server
    container_name: parcels-server
    depends_on:
      - postgres
    restart: unless-stopped
    command: sh -c "yarn run migrate:dev && yarn start:prod"
    environment:
      MODE: server
      PORT: 3001
    env_file:
      - .env
  face:
    build:
      context: face/
      dockerfile: Dockerfile.server
    container_name: parcels-face
    depends_on:
      - server
      - postgres
    restart: unless-stopped
    command: yarn run start
    environment:
      MODE: server
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    container_name: parcel-box-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
networks:
  default:
    name: nginx-proxy
    external: true
