services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: parcels-nginx
    depends_on:
      - face
      - server
      - postgres
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf.dev:/etc/nginx/nginx.conf
  server:
    build:
      context: server/
      dockerfile: Dockerfile.dev
    container_name: parcels-server
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./server/src:/app/src
      - ./server/e2e:/app/e2e
    command: sh -c "yarn run dev"
    environment:
      MODE: testing
      PORT: 3001
    env_file:
      - .env
    ports:
      - 3001:3001
  face:
    build:
      context: face/
      dockerfile: Dockerfile.dev
    container_name: parcels-face
    depends_on:
      - server
      - postgres
    restart: unless-stopped
    volumes:
      - ./face/src:/app/src
      - ./face/public:/app/public
      - ./face/cypress:/app/cypress
    command: yarn run dev
    environment:
      MODE: testing
  postgres:
    image: postgres:16.2
    restart: unless-stopped
    container_name: parcel-box-postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
