import React from 'react'
import type { Metadata } from 'next'
import AdminMainLayout from '../../myPages/admin/AdminMainLayout/AdminMainLayout'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function Layout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return <AdminMainLayout>{children}</AdminMainLayout>
}
